#!/bin/bash
## Copyright ©UDPTeam
## Script to keep-alive your DNSTT server domain record query from target resolver/local dns server
## Run this script excluded to your VPN tunnel (split vpn tunneling mode)
## run command: ./globe-civ3.sh k

## Your DNSTT Nameserver & your Domain `A` Record
NS='ns-sgfree.elcavlaw.com'
A='sgfree.elcavlaw.com'

## Repeat dig cmd loop time (seconds) (positive integer only)
LOOP_DELAY=1

## Add your DNS here
declare -a HOSTS=('124.6.181.12')

## Linux' dig command executable filepath
## Select value: "CUSTOM|C" or "DEFAULT|D"
DIG_EXEC="DEFAULT"
## if set to CUSTOM, enter your custom dig executable path here
CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig

## Number of additional queries to boost DNS
BOOST_QUERIES=3

## Initial TTL value
INITIAL_TTL=30

######################################
######################################
######################################
######################################
######################################
VER=1.0
case "${DIG_EXEC}" in
 DEFAULT|D)
 _DIG="$(command -v dig)"
 ;;
 CUSTOM|C)
 _DIG="${CUSTOM_DIG}"
 ;;
esac
if [ ! $(command -v ${_DIG}) ]; then
 printf "%b" "Dig command failed to run, " \
 "please install dig(dnsutils) or check " \
 "\$DIG_EXEC & \$CUSTOM_DIG variable inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n" && exit 1
fi
endscript() {
 unset NS A LOOP_DELAY HOSTS _DIG DIG_EXEC CUSTOM_DIG T R M TTL
 exit 1
}
trap endscript 2 15
check(){
 for T in "${HOSTS[@]}"; do
  for R in "${A}" "${NS}"; do
   echo "Checking ${R} on ${T}..."
   if [[ -z $(timeout -k 10 10 ${_DIG} @${T} ${R}) ]]; then
     M=31
     echo -e "\e[1;${M}m\$ R:${R} D:${T} - Timed out!\e[0m"
     echo "---------------------------------------"
   else
     M=32
     echo -e "\e[1;${M}m\$ R:${R} D:${T} - Connected!\e[0m"
     echo "---------------------------------------"
   fi
   unset R M
  done
 done
}

## Function to boost DNS queries
boost_dns() {
  for ((i=0; i<"${#HOSTS[@]}"; i++)); do
    for ((j=0; j<${BOOST_QUERIES}; j++)); do
      TTL=$((INITIAL_TTL + j))
      if ${_DIG} +short +ttl=${TTL} @${HOSTS[$i]} ${A} &>/dev/null; then
        echo "Boosted DNS query for ${HOSTS[$i]} - TTL: ${TTL} - Connected!"
      else
        echo "Boosted DNS query for ${HOSTS[$i]} - TTL: ${TTL}"
      fi
    done
    echo "---------------------------------------"
  done
  wait
}

echo "DNSTT Keep-Alive script <Lantin Nohanih>"
echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"
echo "CTRL + C to close script"
[[ "${LOOP_DELAY}" -eq 1 ]] && let "LOOP_DELAY++";

echo "Performing Keep-Alive..."
while true; do
  check
  echo '.--. .-.. . .- ... .     .-- .- .. -'
  sleep ${LOOP_DELAY}
done
